Repository ntu-se7-grp3/garang-guni, pull requests merged in 2024-07, with the labels that each got.

#1 Remove vite templete
  src/App.css
  src/App.jsx
  src/assets/react.svg
Labels: good first issue

#4 Add README info
  README.md
  src/assets/logo.png
Labels: good first issue, GG-1.0.0p, status: pending review

#8 Made changes to project structure files
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
Labels: status: accepted, GG-1.0.0p

#18 Add Routers
  src/App.jsx
  src/layouts/RootLayout.jsx
  src/pages/BookNow.jsx
  src/pages/Contact.jsx
  src/pages/Faq.jsx
  src/pages/Follow.jsx
  src/pages/Jobs.jsx
  src/pages/List.jsx
  src/pages/Login.jsx
  src/pages/Register.jsx
  src/pages/Schedule.jsx
  src/pages/TermsAndCondition.jsx
  src/pages/Welcome.jsx
Labels: enhancement, priority: high, GG-1.0.0p, status: pending review

#14 Add Terms and Conditions Contents
  src/components/TermsAndConditionsContent.jsx
Labels: priority: very low, GG-1.0.0p, status: pending review

#26 Add Contact Us page
  package-lock.json
  package.json
  src/assets/contactUsBanner.png
  src/assets/darkContactUsBanner.png
  src/components/ContactForm.jsx
  src/components/ContactForm.module.css
  src/components/ContactInfoBox.jsx
  src/components/ContactInfoBox.module.css
  src/components/ModalDialog.jsx
  src/index.css
  src/pages/Contact.jsx
  src/pages/Contact.module.css
Labels: enhancement, priority: medium, GG-1.0.0p, status: pending review

#32 Implement login & register functionality
  .env
  package-lock.json
  package.json
  src/App.jsx
  src/components/LoginForm/LoginForm.jsx
  src/components/LoginForm/LoginForm.module.css
  src/components/RegisterForm/RegisterForm.jsx
  src/components/RegisterForm/RegisterForm.module.css
  src/context/user-context.jsx
  src/index.css
  src/layouts/RootLayout.jsx
  src/pages/Auth/Auth.jsx
  src/pages/Auth/Auth.module.css
  src/pages/Login.jsx
  src/pages/Register.jsx
  src/services/auth-api.js
Labels: enhancement, GG-1.0.0p, status: pending review

#34 Feat/home-page
  package-lock.json
  package.json
  src/assets/karungGuni.jpg
  src/assets/karungGuni2.jpg
  src/assets/karungGuni3.jpg
  src/assets/karungGuni4.jpg
  src/components/Footer.jsx
  src/components/ScheduleMap.jsx
  src/components/ScheduleMap.module.css
  src/components/TermsAndConditionsContent.jsx
  src/context/AuthContext.jsx
  src/pages/Contact.jsx
  src/pages/Schedule.jsx
  src/pages/Schedule.module.css
  src/pages/Welcome.jsx
  src/pages/Welcome.module.css
Labels: documentation, enhancement, good first issue, GG-1.0.0p

#24 added schedule page
  src/assets/station1.jpg
  src/assets/station2.jpg
  src/assets/station3.jpg
  src/assets/station4.jpg
  src/assets/station5.jpg
  src/assets/station6.jpg
  src/components/ScheduleMap.jsx
  src/pages/Schedule.jsx
Labels: enhancement, GG-1.0.0p

#37 Add List page
  package.json
  src/api/back-end-api.js
  src/assets/list/bags.svg
  src/assets/list/battery.svg
  src/assets/list/book.svg
  src/assets/list/brochure.svg
  src/assets/list/brokenBulb.svg
  src/assets/list/clothes.svg
  src/assets/list/crayonPaper.svg
  src/assets/list/curtain.svg
  src/assets/list/laptop.svg
  src/assets/list/listBannerText.png
  src/assets/list/magazine.svg
  src/assets/list/newspaper.svg
  src/assets/list/nonRecyclable.svg
  src/assets/list/paper.svg
  src/assets/list/paperTowel.svg
  src/assets/list/phone.svg
  src/assets/list/plant.svg
  src/assets/list/radio.svg
  src/assets/list/recycle-500.svg
  src/assets/list/refrigerator.svg
  src/assets/list/shoes.svg
  src/assets/list/styrofoam.svg
  src/assets/list/tv.svg
  src/components/ListTable.jsx
  src/components/ListTable.module.css
  src/pages/List.jsx
  src/pages/List.module.css
Labels: enhancement, priority: low, GG-1.0.0p, status: pending review

#31 Add Book Now page
  index.html
  package-lock.json
  package.json
  sampleDateAndLocation.json
  sampleKarangGuri.json
  src/assets/recycleCircle.png
  src/components/BookNowContentRow.jsx
  src/components/BookNowContentRow.module.css
  src/components/BookNowEitherOrCheckBox.jsx
  src/components/BookNowEitherOrCheckBox.module.css
  src/components/BookNowForm.jsx
  src/components/BookNowForm.module.css
  src/pages/BookNow.jsx
  src/pages/BookNow.module.css
Labels: enhancement, priority: high, GG-1.0.0p, status: pending review

#38 Fix CSS caused by removing index.css
  src/components/Button.module.css
  src/components/ListTable.module.css
  src/pages/Contact.jsx
  src/pages/Contact.module.css
  src/pages/List.jsx
  src/pages/List.module.css
Labels: bug, enhancement, status: in progress

#40 Add 501 404 error pages
  src/App.jsx
  src/assets/error404.png
  src/assets/error501.png
  src/components/BookNowForm.jsx
  src/pages/Home.jsx
  src/pages/Manage.jsx
  src/pages/NotImplemented.jsx
  src/pages/NotImplemented.module.css
  src/pages/PageNotFound.jsx
  src/pages/PageNotFound.module.css
  src/pages/Profile.jsx
  src/pages/Settings.jsx
  src/pages/TermsAndCondition.jsx
  src/pages/TermsAndPrivacy.jsx
  src/pages/TermsAndPrivacy.module.css
Labels: enhancement, priority: very low, GG-1.0.0p, status: pending review

#42 Fix Css
  src/components/Header.jsx
  src/components/UserPanel.jsx
  src/components/UserPanel.module.css
  src/context/AuthContext.jsx
  src/layouts/RootLayout.jsx
  src/pages/Auth/Auth.jsx
  src/pages/Auth/Auth.module.css
  src/pages/BookNow.module.css
  src/pages/Contact.module.css
  src/pages/NotImplemented.jsx
  src/pages/NotImplemented.module.css
Labels: enhancement, priority: low, GG-1.0.0p, status: pending review

#45 amended photo
  src/assets/karungGuni.jpg
  src/pages/Welcome.module.css
Labels: enhancement

#47 fixed panel handover issue and use panel display
  src/components/Header.jsx
  src/components/Header.module.css
  src/components/SideBar.module.css
  src/context/user-context.jsx
Labels: enhancement
